pipeline {
    agent none
     stages {
            steps {
                sh 'mvn clean package -DskipTests'
            }
     }
        stage('Build Image') {
            steps {
                script {
                	app = docker.build("vinsdocker/selenium-docker")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
			        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
			        	app.push("${BUILD_NUMBER}")
			            app.push("latest")
			        }
                }
            
        }
    }
}
